In [1]:
import pandas as pd

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy as db
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, inspect, func

In [2]:
#Create engine
engine = create_engine("sqlite:///data/chicago_data.sqlite")

In [3]:
# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

In [4]:
#View classes that automap found
Base.classes.keys()

[]

In [5]:
#get table names
inspector = inspect(engine)
inspector.get_table_names()

['chicago_data']

In [6]:
#View columns and types
columns = inspector.get_columns('chicago_data')
for c in columns:
    print(c['name'])

CauseofDeath
CommunityArea
CommunityAreaName
CumulativeDeaths2006-2010
CumulativeDeathsRank
AverageAnnualDeaths2006-2010
AverageCrudeRate2006-2010
AverageCrudeRateLowerCI
AverageCrudeRateUpperCI
CrudeRateRank
AverageAdjustedRate2006-2010
AverageAdjustedRateLowerCI
AverageAdjustedRateUpperCI
AdjustedRateRank
AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010
YPLLRateRANK
WARNING

In [7]:
# Create measurement dataframe
conn = engine.connect()
chi_data = pd.read_sql("SELECT * FROM chicago_data", conn)
chi_data.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
0,All Causes,1,Rogers Park,1741,22,348,614.2,585.3,643.1,51,895.2,852.2,939.3,29,7128,37,
1,All Causes,2,West Ridge,2612,5,522,723.6,695.8,751.4,42,689.9,663.3,717.1,58,6123,49,
2,All Causes,3,Uptown,2542,6,508,879.6,845.4,913.8,31,934,897.5,971.2,24,9147,31,
3,All Causes,4,Lincoln Square,1108,40,222,547,514.8,579.2,60,698.7,657.4,741.3,53,5344,62,
4,All Causes,5,North Center,690,59,138,433,400.7,465.3,68,681.2,630.1,734.3,61,4058,74,

In [8]:
# show data types
print(chi_data.dtypes)

CauseofDeath                                                object
CommunityArea                                               object
CommunityAreaName                                           object
CumulativeDeaths2006-2010                                   object
CumulativeDeathsRank                                        object
AverageAnnualDeaths2006-2010                                object
AverageCrudeRate2006-2010                                   object
AverageCrudeRateLowerCI                                     object
AverageCrudeRateUpperCI                                     object
CrudeRateRank                                               object
AverageAdjustedRate2006-2010                                object
AverageAdjustedRateLowerCI                                  object
AverageAdjustedRateUpperCI                                  object
AdjustedRateRank                                            object
AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010    object
YPLLRateRANK                                                object
WARNING                                                     object
dtype: object

In [9]:
#convert object into integers
chi_data["CumulativeDeaths2006-2010"] = chi_data["CumulativeDeaths2006-2010"].astype(int)

In [10]:
# show updated data types
print(chi_data.dtypes)

CauseofDeath                                                object
CommunityArea                                               object
CommunityAreaName                                           object
CumulativeDeaths2006-2010                                    int32
CumulativeDeathsRank                                        object
AverageAnnualDeaths2006-2010                                object
AverageCrudeRate2006-2010                                   object
AverageCrudeRateLowerCI                                     object
AverageCrudeRateUpperCI                                     object
CrudeRateRank                                               object
AverageAdjustedRate2006-2010                                object
AverageAdjustedRateLowerCI                                  object
AverageAdjustedRateUpperCI                                  object
AdjustedRateRank                                            object
AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010    object
YPLLRateRANK                                                object
WARNING                                                     object
dtype: object

In [11]:
# Filter on Chicago--all
chi_all = chi_data.loc[(chi_data["CommunityAreaName"] == "Chicago")]
chi_all.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
77,All Causes,0,Chicago,97851,,"19,570",715.4,710.9,719.9,,817.4,812.2,822.5,,8371,,
155,All causes in males,0,Chicago,49732,,"9,946",749.3,742.7,755.9,,1003.7,994.6,1012.9,,10833,,
233,All causes in females,0,Chicago,48110,,"9,622",683.3,677.2,689.4,,676.6,670.5,682.7,,5991,,
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,

In [12]:
# remove All Causes
chi_causes = chi_all.loc[(chi_all["CauseofDeath"] != "All Causes")]
chi_causes.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
155,All causes in males,0,Chicago,49732,,"9,946",749.3,742.7,755.9,,1003.7,994.6,1012.9,,10833,,
233,All causes in females,0,Chicago,48110,,"9,622",683.3,677.2,689.4,,676.6,670.5,682.7,,5991,,
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,
472,Breast cancer in females,0,Chicago,1802,,360,25.6,24.4,26.8,,26.1,24.9,27.4,,326,,

In [13]:
# remove all causes in males
chi_updated = chi_causes.loc[(chi_causes["CauseofDeath"] != "All causes in males")]
chi_updated.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
233,All causes in females,0,Chicago,48110,,"9,622",683.3,677.2,689.4,,676.6,670.5,682.7,,5991,,
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,
472,Breast cancer in females,0,Chicago,1802,,360,25.6,24.4,26.8,,26.1,24.9,27.4,,326,,
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,

In [14]:
# remove all causes in females
chi_new = chi_updated.loc[(chi_updated["CauseofDeath"] != "All causes in females")]
chi_new.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,
472,Breast cancer in females,0,Chicago,1802,,360,25.6,24.4,26.8,,26.1,24.9,27.4,,326,,
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,
625,Colorectal cancer,0,Chicago,2496,,499,18.2,17.5,18.9,,21.2,20.3,22,,147,,

In [15]:
# remove all causes in prostate cancer
chi_final = chi_new.loc[(chi_new["CauseofDeath"] != "Prostate cancer in males")]
chi_final.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,
472,Breast cancer in females,0,Chicago,1802,,360,25.6,24.4,26.8,,26.1,24.9,27.4,,326,,
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,
625,Colorectal cancer,0,Chicago,2496,,499,18.2,17.5,18.9,,21.2,20.3,22,,147,,

In [16]:
# filter out breast cancer
chi_again = chi_final.loc[ (chi_final["CauseofDeath"] != "Breast cancer in females")] 
chi_again.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,
625,Colorectal cancer,0,Chicago,2496,,499,18.2,17.5,18.9,,21.2,20.3,22,,147,,
701,Coronary heart disease,0,Chicago,17090,,"3,418",124.9,123,126.8,,145.5,143.3,147.7,,807,,

In [17]:
# filter out colorectal cancer
chi_next = chi_again.loc[ (chi_again["CauseofDeath"] != "Colorectal cancer")] 
chi_next.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
312,Alzheimers disease,0,Chicago,1741,,348,12.7,12.1,13.3,,15.3,14.6,16.1,,6,,
391,Assault (homicide),0,Chicago,2245,,449,16.4,15.7,17.1,,14.9,14.3,15.5,,804,,
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,
701,Coronary heart disease,0,Chicago,17090,,"3,418",124.9,123,126.8,,145.5,143.3,147.7,,807,,
779,Diabetes-related,0,Chicago,3125,,625,22.8,22,23.6,,26.5,25.6,27.4,,195,,

In [28]:
# filter out lung cancer
chi_final2 = chi_next.loc[ (chi_next["CauseofDeath"] != "Lung cancer")] 

#sort values
chi_final2 = chi_final2.sort_values(["CumulativeDeaths2006-2010"], ascending=False)

chi_final2.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,
701,Coronary heart disease,0,Chicago,17090,,"3,418",124.9,123,126.8,,145.5,143.3,147.7,,807,,
1325,Stroke (cerebrovascular disease),0,Chicago,4941,,988,36.1,35.1,37.1,,42.6,41.4,43.8,,218,,
935,"Injury, unintentional",0,Chicago,3922,,784,28.7,27.8,29.6,,29.9,28.9,30.8,,881,,
779,Diabetes-related,0,Chicago,3125,,625,22.8,22,23.6,,26.5,25.6,27.4,,195,,

In [20]:
# find leading cause of death
chi_max = chi_final2["CumulativeDeaths2006-2010"].max()
chi_max

22758

In [23]:
# total deaths
chi_total = chi_final2["CumulativeDeaths2006-2010"].sum()
chi_total

62749

In [31]:
# percentage of total
chi_final2["Percentage of Total"] = ((chi_final2["CumulativeDeaths2006-2010"] / chi_final2["CumulativeDeaths2006-2010"].sum()) * 100)
chi_final2.head()

,CauseofDeath,CommunityArea,CommunityAreaName,CumulativeDeaths2006-2010,CumulativeDeathsRank,AverageAnnualDeaths2006-2010,AverageCrudeRate2006-2010,AverageCrudeRateLowerCI,AverageCrudeRateUpperCI,CrudeRateRank,AverageAdjustedRate2006-2010,AverageAdjustedRateLowerCI,AverageAdjustedRateUpperCI,AdjustedRateRank,AverageAnnualYearsofPotentialLifeLost(YPLL)Rate2006-2010,YPLLRateRANK,WARNING,Percentage of Total
545,Cancer (all sites),0,Chicago,22758,,"4,552",166.4,164.2,168.6,,191.3,188.8,193.8,,1536,,,36.268307
701,Coronary heart disease,0,Chicago,17090,,"3,418",124.9,123,126.8,,145.5,143.3,147.7,,807,,,27.235494
1325,Stroke (cerebrovascular disease),0,Chicago,4941,,988,36.1,35.1,37.1,,42.6,41.4,43.8,,218,,,7.874229
935,"Injury, unintentional",0,Chicago,3922,,784,28.7,27.8,29.6,,29.9,28.9,30.8,,881,,,6.250299
779,Diabetes-related,0,Chicago,3125,,625,22.8,22,23.6,,26.5,25.6,27.4,,195,,,4.980159

In [35]:
chi_stats = (chi_final2["CauseofDeath"], chi_final2["Percentage of Total"])
chi_stats

(545                                    Cancer (all sites)
 701                                Coronary heart disease
 1325                     Stroke (cerebrovascular disease)
 935                                 Injury, unintentional
 779                                      Diabetes-related
 1013    Kidney disease (nephritis, nephrotic syndrome ...
 391                                    Assault (homicide)
 858                                       Firearm-related
 312                                    Alzheimers disease
 1092                          Liver disease and cirrhosis
 1403                      Suicide (intentional self-harm)
 Name: CauseofDeath, dtype: object, 545     36.268307
 701     27.235494
 1325     7.874229
 935      6.250299
 779      4.980159
 1013     4.267797
 391      3.577746
 858      3.306826
 312      2.774546
 1092     2.052622
 1403     1.411975
 Name: Percentage of Total, dtype: float64)